In [1]:
import pandas as pd

##  Reading data

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.head()

Fever  BodyPain  Age  RunnyNose  DiffBreath  InfectionProb
0  100.261224         0   60          1           0              1
1   98.401881         1   42          0           0              0
2  101.012020         1   74          0           0              0
3   98.525752         1   87          1           1              1
4  100.583094         1   59          0          -1              0

In [4]:
df.tail()

Fever  BodyPain  Age  RunnyNose  DiffBreath  InfectionProb
4995   99.321207         1   80          0          -1              0
4996  101.192087         1   96          0           1              0
4997  101.302608         1   56          1           0              1
4998   98.154604         1   99          0           0              1
4999  101.123400         1   78          0           1              0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Fever          5000 non-null   float64
 1   BodyPain       5000 non-null   int64  
 2   Age            5000 non-null   int64  
 3   RunnyNose      5000 non-null   int64  
 4   DiffBreath     5000 non-null   int64  
 5   InfectionProb  5000 non-null   int64  
dtypes: float64(1), int64(5)
memory usage: 234.5 KB


In [6]:
df['DiffBreath'].value_counts()    ## -1 -->no problem  ,0--> low problem in breathing , 1-->Extreme prob

-1    1723
 1    1647
 0    1630
Name: DiffBreath, dtype: int64

In [7]:
df.describe()

Fever     BodyPain          Age    RunnyNose   DiffBreath  \
count  5000.000000  5000.000000  5000.000000  5000.000000  5000.000000   
mean    100.011858     0.491400    50.741200     0.491600    -0.015200   
std       1.154083     0.499976    28.947494     0.499979     0.820916   
min      98.001514     0.000000     1.000000     0.000000    -1.000000   
25%      99.006029     0.000000    25.000000     0.000000    -1.000000   
50%      99.993522     0.000000    52.000000     0.000000     0.000000   
75%     101.029613     1.000000    76.000000     1.000000     1.000000   
max     101.999877     1.000000   100.000000     1.000000     1.000000   

       InfectionProb  
count    5000.000000  
mean        0.489600  
std         0.499942  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         1.000000  
max         1.000000

## Train Test Splitting

In [8]:
import numpy as np

In [9]:
def data_split(data,ratio):
    np.random.seed(42) #to fix the shuffled values so that the rest test data is not matched with any of the shuffled data.
    shuffled = np.random.permutation(len(data)) #it shuffles the length of data in random permutation.
    test_set_size = int(len(data) * ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

    

In [10]:
a = np.random.permutation(7)
print(a)
a[:3] ## prints from starting to index 2.
#a[3:]   ## print index 3 to last

[1 0 4 5 2 3 6]


array([1, 0, 4])

In [11]:
train,test = data_split(df, 0.2)

In [12]:
train

Fever  BodyPain  Age  RunnyNose  DiffBreath  InfectionProb
4227  100.550535         1   98          0           0              0
4676   98.032866         1   68          0          -1              1
800    98.572701         1   80          1           1              0
3671  101.119312         0   44          0           0              0
4193  100.963009         1   14          1          -1              0
...          ...       ...  ...        ...         ...            ...
4426  100.796408         1   49          1           1              0
466    99.708709         0   20          0           1              0
3092  101.914742         0   57          0           0              0
3772  100.641950         1   59          0          -1              1
860    98.921359         0    7          1           0              0

[4000 rows x 6 columns]

In [13]:
test

Fever  BodyPain  Age  RunnyNose  DiffBreath  InfectionProb
1501  100.450992         1   61          1          -1              0
2586   99.847952         0   85          1           0              1
2653   98.116985         1   14          1           0              0
1055   99.895627         1   11          0          -1              1
705   101.821306         1   50          0           1              1
...          ...       ...  ...        ...         ...            ...
4711  100.710898         1   41          1           1              1
2313  100.437816         0   90          0           0              1
3214  101.888759         0   57          1           0              1
2732  101.667690         1   95          1           1              1
1926   98.392763         1   36          0           0              1

[1000 rows x 6 columns]

In [14]:
X_train = train[['Fever','BodyPain','Age','RunnyNose','DiffBreath']].to_numpy()
X_test = test[['Fever','BodyPain','Age','RunnyNose','DiffBreath']].to_numpy()

In [15]:
Y_train = train[['InfectionProb']].to_numpy().reshape(4000,)
Y_test = test[['InfectionProb']].to_numpy().reshape(1000,)

In [16]:
Y_train

array([0, 1, 0, ..., 0, 1, 0], dtype=int64)

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
clf = LogisticRegression()
clf.fit(X_train, Y_train) ## fitting the training data

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [19]:
inputFeatures = [100,1,89,-1,1]
infProb = clf.predict_proba([inputFeatures])[0][1]   ## gives prediction probability(true% ,False%)

In [20]:
infProb

0.4598093485677871